version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g yarn
      - yarn install
  build:
    commands:
      - yarn run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: ./